services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: ./PruebaIngreso-main
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "8080:8080"

  front:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./apuestas-front:/usr/src/app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  pgdata:
